### ISSUE TITLE
Security issues? 

### ISSUE THREAD

**Issue by DataStrategist** [roryg/ghostwriter#107]
Hi, I'm using the Hugo port of ghostwriter. I'm getting some security notifications when I publish my site: 
![image](https://user-images.githubusercontent.com/8094091/78768515-ec476500-7983-11ea-8a62-9c71d7a97de9.png)

I opened [an issue](https://github.com/jbub/ghostwriter/issues/73) in the hugo version of this repo but apparently there's some work to be done on your end?

**Comment by tylerfontaine** [comment]
These are node dependencies, not theme dependencies. It's unclear to me why the theme directory even has the yarn.lock file, but i'm not familiar enough with hugo to know if it's needed, or just a .gitignore oversight.

In either case, that would be upstream in hugo to ensure using up-to-date packages, not in this theme.

**Comment by DataStrategist** [comment]
ok thanks, will feed this back.

**Comment by jbub** [comment]
@DataStrategist you misunderstood my point, by upstream packages i meant those javascript packages i do not have control of.

**Comment by tylerfontaine** [comment]
Oops. Updated my comment - node, not rails. :D Thanks, @jbub

**Comment by jbub** [comment]
And just be clear, im using node packages for converting scss to css. And then webpack to bundle those. :)
