### ISSUE TITLE
External links in the navigation bar

### ISSUE THREAD

**Issue by Penderworth** [roryg/ghostwriter#70]
Is is at all possible to link to an external site in the top navigation bar? I'm trying to do this:

`<li class="site-nav-item"><a class="js-ajax-link" title="Starfront Photography |  500px" href="http://starfront.500px.com">Photography</a></li>`

Since ajax is active, it just loads infinitely. Any ideas?

**Comment by roryg** [comment]
Removing `class="js-ajax-link"` should do the trick :smile:

**Comment by Penderworth** [comment]
@roryg Lol. Can't believe I missed the obvious bit. Thank you!
