### ISSUE TITLE
How to make "Browse Posts" the default landing page

### ISSUE THREAD

**Issue by jackmaht** [roryg/ghostwriter#74]
Hi,

I love the theme so far, but am wondering if there is the ability to make the "Browse Posts" option the default when you land on the main page. How can this be done?

Best,

Jack

**Comment by Gheek** [comment]
Just comment out lines 31-32 of script.js in /assets/js/ :

```
// $latestPost.show();
// $postIndex.hide(); 
```

**Comment by jackmaht** [comment]
Perfect. Thank you @Gheek !
