### ISSUE TITLE
Navigation broken when using https

### ISSUE THREAD

**Issue by Gheek** [roryg/ghostwriter#75]
I got a problem with the "browse post" and "latest post" navigation as i switched over to https.
When you try to browse posts, the loading animation is running, but nothing is happening.

Console prints this:

```Uncaught SecurityError: Failed to execute 'pushState' on 'History': A history state object with URL 'http://dontspyon.me/' cannot be created in a document with origin 'https://dontspyon.me'. ```

I tried to fix it by altering the href-attribute of the links from ```{@blog.title}``` to ```{url absolute="true"}```. This fixed the displayed error, but navigation is still broken.

Any ideas, how to fix it?

**Comment by roryg** [comment]
Have you edited your Ghost config file to use https in the url property? It should be:

    production: {
        url: 'https://dontspyon.me',

Remember to restart Ghost after editing it.

**Comment by Gheek** [comment]
Sorry, i forgot to mention that. I tried that at first but then I got a ```ERR_TOO_MANY_REDIRECTS```.

**Comment by roryg** [comment]
Hmm strange I thought that would work. If I open up the chrome inspector and change the `href` attributes for the "Latest Post" and "Browse Posts" link to `https://dontspyon.me` (no trailing slash) it works and loads the pages as expected. I'm not sure how to get Ghost to output the links like that but as an alternative you could try just hard coding the links into the template files.

**Comment by Gheek** [comment]
Allright, I'll hard code then. That's totally fine for me - thank you!
