### ISSUE TITLE
Will Ghostwriter be affected by the jQuery drop in the Theme API

### ISSUE THREAD

**Issue by arcfide** [roryg/ghostwriter#82]
An announcement on the Ghost Theme Develepor's list has indicated that jQuery will soon be dropped. I have not examined the Ghostwriter code carefully and would like to know whether the theme will be affected by this breaking change? If so, is there a fix in place?

**Comment by postblue** [comment]
[Link to the announcement](http://dev.ghost.org/no-more-jquery/).

As you can see in `default.hbs`, here's the `<script>` calls:

```hbs
{{! Ghost outputs important scripts and data with this tag }}
    {{ghost_foot}}

    <script type="text/javascript" src="{{asset "js/jquery.history.js"}}"></script>
    <script type="text/javascript" src="{{asset "js/nprogress.js"}}"></script>
    <script type="text/javascript" src="{{asset "js/jquery.fitvids.js"}}"></script>
    <script type="text/javascript" src="{{asset "js/scripts.js"}}"></script>
```

Ghostwriter seems to be lacking it's own jQuery files, indeed, but it's easy to include. :)
@roryg Do you want to work on it or should I make a Pull Request (a few are pending!)?

**Comment by roryg** [comment]
I've added a local copy of jQuery that will only load when Ghost removes their copy - https://github.com/roryg/ghostwriter/blob/master/default.hbs#L76

Thanks for those PRs @postblue I've merged most of them in but rejected the local font ones as I'd prefer to load them from CDNs.
