### ISSUE TITLE
Delete default dots below published date

### ISSUE THREAD

**Issue by bradam** [roryg/ghostwriter#87]
Hello,

Is it possible to delete the serials of dots below the published date?
![dots](http://i.imgur.com/rEV93aF.png)

Thanks and keep up the good work!

**Comment by Penderworth** [comment]
@bradam Those are the `border-bottom` rule of `.post-date:after, .blog-description:after`. I would give you line numbers, but they won't help since I have a highly-customized version of this theme. Simply comment out the rule I mentioned by surrounding it with `/* */` and you should be all set.

**Comment by bradam** [comment]
@Penderworth Wow, thanks mate, thats solve my problem!
