### ISSUE TITLE
Changing default main page

### ISSUE THREAD

**Issue by classicyuppie** [roryg/ghostwriter#92]
How do I change the default page that it lands on when I go to my site's URL?

By default, the theme will place me on the most recent post, which might work for some folks, but I'd rather have the archive page as the main landing page when you go to www.example.com.

Is this possible?

**Comment by roryg** [comment]
Yes, it's very easy you just need to swap the `hide` and `show` on these two lines around - https://github.com/roryg/ghostwriter/blob/master/assets/js/scripts.js#L31-L32 - to:
```
$latestPost.hide();
$postIndex.show();
```
