### ISSUE TITLE
1.0 compatibility

### ISSUE THREAD

**Issue by postblue** [roryg/ghostwriter#99]
There's a few changes in the upcoming 1.0 release that we need to fix. According to [gscan](https://gscan.ghost.org/):

> # Must fix
> 
> Replace the `{{image}}` helper with `{{feature_image}}`, `{{cover_image}}` or `{{profile_image}}`.
> 
> * `author.hbs`: Please remove or replace `{{image}}` from this template
> * `page.hbs:` Please remove or replace `{{image}}` from this template
> * `partials/post-content.hbs`: Please remove or replace `{{image}}` from this template
> 
> Replace the `{{#if image}}` helper with `{{#if feature_image}}`, or `{{#if cover_image}}`, or `{{#if profile_image}}`.
> 
> * `author.hbs`: Please remove or replace `{{#if image}}` from this template
> *  `page.hbs`: Please remove or replace `{{#if image}}` from this template
> *  `partials/post-content.hbs`: Please remove or replace `{{#if image}}` from this template
> 
> Usage of `{{meta_description}}` in HTML `head` is deprecated.
> 
> * `default.hbs`: Please remove or replace `{{meta_description}}` from this template
> 
> package.json `author.email` is required.
> 
> package.json `author.email` must be valid.
> 
> package.json `name` must be lowercase.
> 
> # Consider fixing
> 
> package.json `config.page_per_post` is recommended. Otherwise, it falls back to 5.

**Comment by roryg** [comment]
Thanks @postblue I'll take a look at this soon

**Comment by postblue** [comment]
You're welcome! As [Ghost 0.11.11](https://dev.ghost.org/ghost-0-11-11/) adds forward compatibility for Ghost 1.0 themes, I'll give it a shot soon to.

**Comment by roryg** [comment]
All changes have been made so Ghostwriter will now be ready for Ghost 1.0 🙂
